### PR TITLE
Generated parent build

### PR DESCRIPTION
**Pull request by popeindustries**
(see #105)

Adds support for dynamically generating the contents of a parent build based on the shared/common dependencies of it's children. 

~~Triggered by specifying `common` or `shared` as `input`~~ Triggerd by specifying `children:common` or `children:shared` as `input`:

```JS
{ 
  build:  [
    {
      input: 'children:shared',
      output: 'www/shared.js',
      children: [
        {
          input: 'src/foo.js',
          output: 'www'
        },
        {
          input: 'src/bar.js',
          output: 'www'
        }
      ]
    }
  ]
}
```

Dependencies common to `src/foo.js` and `src/bar.js` will be moved to the `common` build bundle.

This would also result in the same:

```JS
{ 
  build:  [
    {
      input: 'children:shared',
      output: 'www/shared.js',
      children: [
        {
          input: [ 'src/foo.js', 'src/bar.js'],
          output: 'www'
        }
      ]
    }
  ]
}
```

As would this (assuming only 2 files in 'src'):

```JS
{ 
  build:  [
    {
      input: 'children:shared',
      output: 'www/shared.js',
      children: [
        {
          input:  'src/*.js',
          output: 'www'
        }
      ]
    }
  ]
}
```

~~Currently using a conservative intersection algorithm that requires all immediate children have the same dependency before it's included. This could (should?) be relaxed to enable including a dependency if it's in at least 2 children. Doing so, it would then be possible to also take into account deeply nested children.~~

### CODE REVIEW

**Comment by popeindustries** [comment]
@eirikbacker any thoughts on the config syntax (`'common'`)? Other options would be dropping `input` completely, but that feels a little unintuitive.

**Comment by eirikbacker** [comment]
@popeindustries Feels kind of magic.. Still magic, but would "bundle" be a better param?

**Comment by popeindustries** [comment]
@eirikbacker as in `input: 'bundle'`? The only "new" thing here is specifying an `input` that means: "the content of this bundle is based on all the dependencies that overlap between my children"

**Comment by popeindustries** [comment]
Another (more powerful) idea: add a prefix to show "here be magic", and open the way for more possibilities:

`input: 'calc:shared'` => same as above
`input: 'calc:node_modules/*'` => move all node_modules dependencies to parent
`input: 'calc:**/lib.js'` => glob match

**Pull request merged**
